openapi: 3.0.1
info:
  title: Bakery
  description: 'This is a sample Bakery server created by Santiago and Yvonne.'
#  termsOfService: http://swagger.io/terms/
#  contact:
#    email: apiteam@swagger.io
#  license:
#    name: Apache 2.0
#    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
externalDocs:
  description: Find out more about our bakery
#  url: http://swagger.io
tags:
  - name: pastry
    description: Everything about our pastries

components:
  schemas:
    Pastry:
      type: object
      properties:
        name:
          type: string
        price:
          type: integer
        gluten-free:
          type: boolean
        ingredients:
          type: array
servers:
  - url: https://localhost:/8080

paths:
  /pastries:
    get:
      tags:
        - pastry
      summary: Find all pastries
      description:
      responses:
        '200':
          description: Successful operation
    post:
      tags:
        - pastry
      summary: Add a new pastry to inventory
      description: Pastry object that needs to be added to inventory
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pastry'
        required: true
      responses:
        '200':
          description: Successful operation
  /pastries/{name}:
    get:
      tags:
        - pastry
      summary: Find pastry by name
      description: Returns a single pastry
      parameters:
        - name: pastryName
          in: path
          description: Name of pastry to return
          required: true
      responses:
        '200':
          description: Successful operation
    patch:
      tags:
        - pastry
      summary: Edit pastry by name
      description: Edit a pastry by name
      parameters:
        - name: pastryName
          in: path
          description: Name of pastry to edit
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pastry'
      responses:
        '200':
          description: Successful operation
    delete:
      tags:
        - pastry
      summary: Delete pastry by ID
      parameters:
        - name: pastryName
          in: path
          description: Name of pastry to delete
          required: true
      responses:
        '200':
          description: Successful operation
